apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service custom-metric"]'
  name: custom-metric
  labels:
     name: custom-metric
spec:
  replicas: 3
  selector:
    matchLabels:
         name: custom-metric
  template:
    metadata:
      labels:
         name: custom-metric
    spec:
      containers:
      - name: custom-metric
        image: dfedoruk/custom-metric
        ports:
        - containerPort: 8181