apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: custom-metric
  labels:
     name: custom-metric
spec:
  replicas: 3
  template:
    metadata:
      labels:
         name: custom-metric
    spec:
      containers:
      - name: custom-metric
        image: dfedoruk/custom-metric:1.0.0
        ports:
        - containerPort: 8181
